[font]
  normal = { family = "Hack Nerd Font", style = "Regular" }
  size = 16.0
  bold = { family = "Hack Nerd Font", style = "Bold" }
  italic = { family = "Hack Nerd Font", style = "Italic" }

[colors.primary]
background = "0x000000"
foreground = "0xabb2bf"

[colors.normal]
black   = "0x282c34"
red     = "0xe06c75"
green   = "0xbbffbb"
yellow  = "0xe5c07b"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0xabb2bf"

[colors.bright]
black   = "0x5c6370"
red     = "0xe06c75"
green   = "0xbbffbb"
yellow  = "0xe5c07b"
blue    = "0x61afef"
magenta = "0xc678dd"
cyan    = "0x56b6c2"
white   = "0xffffff"

[window]
dynamic_title = true

