[font]
  normal = { family = "Hack", style = "Regular" }
  size = 16.0
  bold = { family = "Hack", style = "Bold" }
  italic = { family = "Hack", style = "Italic" }
[colors.bright]
black = "0x665c54"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0x8ec07c"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xeeeeee"
yellow = "0xfad02e"

[colors.normal]
black = "0x000000"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0x8ec07c"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xebdbb2"
yellow = "0xfad02e"

[colors.primary]
background = "0x101010"
foreground = "0xebdbb2"

[window]
dynamic_title = true

